# Generated by Django 4.2.10 on 2024-04-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=220)),
                ('data_response', models.CharField(max_length=500)),
                ('time_response', models.CharField(max_length=40)),
            ],
        ),
    ]
